name: CI

on:
  push:
    branches:
     - master
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Java 8
        uses: actions/setup-java@v2
        with:
          java-version: "8"
          distribution: adopt
          cache: maven
      - name: Setup Git
        run: |
          git config --global user.email "ci@example.com"
          git config --global user.name "GitHub CI"
      - name: Build SportPaper
        run: bash sportpaper build
      - name: Upload SportPaper JAR
        uses: actions/upload-artifact@v2
        with:
          name: sportpaper-1.8.8-R0.1-SNAPSHOT.jar
          path: SportPaper-Server/target/sportpaper-1.8.8-R0.1-SNAPSHOT.jar
          if-no-files-found: error
      - name: Publish SportPaper JAR
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        run: mvn deploy --settings settings.xml
        env:
          REPO_USERNAME: ${{ secrets.REPO_USERNAME }}
          REPO_PASSWORD: ${{ secrets.REPO_PASSWORD }}
